import { chromium } from "playwright";
const BASE = "http://localhost:3000";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await p.fill("#email", "aditya@proviyaa.example");
await p.fill("#password", "Proviyaa@2026");
await p.click('button[type="submit"]');
await p.waitForURL(/\/admin/, { timeout: 25000 });
await p.goto(`${BASE}/admin/success`, { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
const link = await p.locator('a[href^="/admin/success/"]').first().getAttribute("href");
await p.goto(`${BASE}${link}`, { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.getByRole("button", { name: /Draft the handoff brief/ }).click();
await p.waitForTimeout(20000);
await p.goto(`${BASE}${link}`, { waitUntil: "networkidle" });
await p.waitForTimeout(1800);
await p.locator("text=Handoff brief").first().scrollIntoViewIfNeeded();
await p.screenshot({ path: process.argv[2] + "/v11-bot-draft.jpg", type: "jpeg", quality: 84 });
console.log("done:", link);
await b.close();
